server: 
    port: 8080

file.upload-dir: C:/fatec_uploads/

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/dbzinho
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
        initialize: true 
    
    jpa:
        hibernate:
            ddl-auto: update 
        generate-ddl: true
        show-sql: true