server: 
    port: 8080

file.upload-dir: src/main/resources/static/uploads/

spring:
    datasource:
        url: jdbc:postgresql://dpg-d4add4idbo4c73c9q2eg-a.oregon-postgres.render.com:5432/databasereserva
        username: databasereserva_user 
        password: jgwlvInhwZ0DAH4NEQfmx0w6RlnGhhiy
        driver-class-name: org.postgresql.Driver
        initialize: true
    
    jpa:
        hibernate:
            ddl-auto: update
        generate-ddl: true
        show-sql: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
servlet:
        multipart:
            max-file-size: 10MB       
            max-request-size: 10MB




# server: 
#     port: 8080

# # file.upload-dir: C:/fatec_uploads/
# file.upload-dir: src/main/resources/static/uploads/

# spring:
#     datasource:
#         url: jdbc:postgresql://localhost:5432/dbzinho
#         username: postgres
#         password: root
#         driver-class-name: org.postgresql.Driver
#         initialize: true 
    
#     jpa:
#         hibernate:
#             ddl-auto: update 
#         generate-ddl: true
#         show-sql: true

#     servlet:
#         multipart:
#             max-file-size: 10MB       
#             max-request-size: 10MB